### ISSUE TITLE
User token concerns

### ISSUE THREAD

**Issue by ghost** [jclark754/MesoPy#1]
Right now all requests made to the MesoWest API use the same API Key/token. Need to talk with MesoWest folks about how they'd like to track users of MesoPy. Could leave it as is or create the option for a user to generate a token off the master key or input their own key/token.

**Comment by jclark754** [comment]
best practice here after doing a bit of research suggests storing this info as environment variables in the config.py file. going to proceed with this thinking.

**Comment by ghost** [comment]
created a class so when user creates instance of Meso object they pass in the API key. Users will need to request a Key/token combo from the MesoWest folks...I'll note this in the README and docs.
