### ISSUE TITLE
Unnecessary kwags['network']='1,2' on station_list() call?

### ISSUE THREAD

**Issue by carlosandrade** [jclark754/MesoPy#9]
Hi, 

I was experimenting with MesoWest API directly on Oahu Island and noticed the following API request: 

http://api.mesowest.net/v2/stations/metadata?bbox=-158.42,21.18,-157.63,22.26&token=1234567890

which imposes a bounding box on the island had a different amount of stations than my call on station_list(). Specifically it narrowed down to 22. 

Further inspection on the MesoPy code made me realize the hard-coded parameter: 

kwags['network']='1,2'

Which is optional on the API call (http://mesowest.org/api/docs/) but apparently required on the code. Commenting the following parameter fixed the issue. Is there any particular reason for this restriction?

**Comment by ghost** [comment]
Hi @carlosandrade!
Good catch on that. I think originally when I was testing the library I set that to filter out some inactive stations and such to cut down on response time and the amount of data being returned. Anyway, I've removed it and updated the func docstring. Expect MesoPy to gain a ton of features soon...we're working on adding a great deal of new ways to play with the API right now.
